name: 'playground'
version: '1.0.0'
config-version: 2

#in case of emergency delete
dbt-cloud:
  project-id: 70471823406633

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target' # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_packages'

models:
  playground:
    # Applies to all files under models/
    +materialized: table
    +required_tests: { 'unique.*|not_null': 1 }
